name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: EC2-DEV
    
    steps:
      - uses: actions/checkout@v3 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            AWS_REGION : ${{ secrets.AWS_DEFAULT_REGION  }}
            SSH_KEY : ${{ secrets.SSH_KEY  }}
            
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan "${{ secrets.HOSTNAME  }}" >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.AWS_PRIVATE_KEY }}"
          echo "$PRIVATE_KEY" >  ~/.ssh/private.key
          sudo chmod 400  ~/.ssh/private.key
          echo $PWD          
          
      - name: SSH into DO and run
        run: |
          cat ~/.ssh/known_hosts
          ls -al ~/.ssh
          echo "$USER_NAME@$HOSTNAME"
          # ssh -i ~/.ssh/private.key -o ConnectTimeout=10 -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME
          
      
          
          
          
