name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: EC2-DEV
    
    steps:
      - uses: actions/checkout@v3 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            AWS_REGION : ${{ secrets.AWS_DEFAULT_REGION  }}
            SSH_KEY : ${{ secrets.SSH_KEY  }}
            
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan "${{ secrets.HOSTNAME  }}" >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.AWS_PRIVATE_KEY }}"
          echo "$PRIVATE_KEY" > ../private.key
          sudo chmod 400 ../private.key
          cd ~/.ssh
          echo $PWD
          tree
          ls -al ../
          
      - name: SSH into DO and run
        run: |
          ssh -i ../private.key -o UserKnownHostsFile=/github/home/.ssh/known_hosts -tt ubuntu@ec2-35-180-196-172.eu-west-3.compute.amazonaws.com "echo test > testfile1"
          
          
      
          
          
          
