name: CI/CD counter app

env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
  HOSTNAME : ${{ secrets.HOSTNAME  }}
  USER_NAME : ${{ secrets.USER_NAME  }}
  AWS_REGION : ${{ secrets.AWS_DEFAULT_REGION  }}
  SSH_KEY : ${{ secrets.SSH_KEY  }}

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: EC2-DEV
    
    steps:
      - uses: actions/checkout@v3 
      - name: SSH connexion
            
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan $HOSTNAME >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< $PRIVATE_KEY
          echo "$PRIVATE_KEY" >  ~/.ssh/private.key
          sudo chmod 400  ~/.ssh/private.key
          # echo $PWD
          # cat ~/.ssh/known_hosts
          
      - name: Deploy in EC2
        run: |
          # ls -al ~/.ssh
          # echo "$USER_NAME@$HOSTNAME"
          ssh -i ~/.ssh/private.key -o ConnectTimeout=10 -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME '
          echo "========================= connect ok !!!!! =============="
          cd /home/ubuntu/CounterApp &&
          git checkout master &&
          git fetch --all &&
          git reset --hard origin/master &&
          git pull origin master &&
          sudo docker-compose -f docker-compose.prod.yml up -d --build 
          '
