name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: EC2-DEV
    
    steps:
      - uses: actions/checkout@v3 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            AWS_REGION : ${{ secrets.AWS_DEFAULT_REGION  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 400 private_key.pem
          ssh -i "private_key.pem" ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .

            cd /home/ubuntu/CounterApp &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            docker-compose -f docker-compose.prod.yml up -d --build 
          '
